name: posproject
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0' 

dependencies:
  get:
  flutter:    
    sdk: flutter
  intl: ^0.17.0
  provider: ^6.0.0  
  url_launcher: ^6.0.20
  blue_thermal_printer:
  pdf: ^3.6.2
  printing: ^5.9.0
  sqflite: ^2.0.0
  path_provider: ^2.0.6  
  path: any
  sqflite_common_ffi: 




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
     -  assets/shoplogo.png
     -  assets/yu.png
     -  assets/massage.gif
     -  assets/massage2.gif
     -  assets/customer.png
     -  assets/yuEmployee.jpg
     -  assets/pos.png
     -  assets/pos.gif
     -  assets/customer1.png
     -  assets/facebook.jpg

  uses-material-design: true
